Fix Windows permissions error by using AppData directory
Resolves PermissionError when trying to create templates directory
in Program Files. Changed default directories to use user's AppData
folder instead of installation directory.

Changes:
- settings.js: Use app.getPath('userData') for default directories
  (Windows: C:\Users\<user>\AppData\Roaming\ARGUS)
- main.js: Copy bundled templates to user directory on first run
- main.js: Update setup dialog text to clarify storage location

Fixes error:
PermissionError: [WinError 5] Access is denied: 'C:\Program Files\ARGUS\templates'